### ISSUE TITLE
Ruby gems only shows until version 0.1.6

### ISSUE THREAD

**Issue by rodolphofreire** [lmorais/zenvia-ruby#6]
Could you please update your gem in ruby gems to version 0.1.8?

**Comment by danielmoral** [comment]
Estou com o mesmo problema! não consigo atualizar a versão.

**Comment by meonthewire** [comment]
Gem updated to version 0.1.8 
Could you try to update?
@rodolphofreire @danielmoral

**Comment by danielmoral** [comment]
Yes! It's Ok!

**Comment by danielmoral** [comment]
Thank you

**Comment by meonthewire** [comment]
:smiley: :tada:

**Comment by rodolphofreire** [comment]
Worked for me too
